# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gtui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1253, 794)
        self.title1 = QtWidgets.QLabel(Dialog)
        self.title1.setGeometry(QtCore.QRect(550, 70, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title1.setFont(font)
        self.title1.setText("")
        self.title1.setObjectName("title1")
        self.title2 = QtWidgets.QLabel(Dialog)
        self.title2.setGeometry(QtCore.QRect(580, 70, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.title2.setFont(font)
        self.title2.setObjectName("title2")
        self.reButton = QtWidgets.QPushButton(Dialog)
        self.reButton.setGeometry(QtCore.QRect(30, 20, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reButton.setFont(font)
        self.reButton.setObjectName("reButton")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(270, 150, 711, 421))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.video = QtWidgets.QLabel(self.frame)
        self.video.setGeometry(QtCore.QRect(0, 0, 711, 421))
        self.video.setObjectName("video")
        self.peopleButton = QtWidgets.QPushButton(Dialog)
        self.peopleButton.setGeometry(QtCore.QRect(300, 650, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.peopleButton.setFont(font)
        self.peopleButton.setObjectName("peopleButton")
        self.carButton = QtWidgets.QPushButton(Dialog)
        self.carButton.setGeometry(QtCore.QRect(690, 650, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.carButton.setFont(font)
        self.carButton.setObjectName("carButton")

        self.retranslateUi(Dialog)
        self.carButton.clicked.connect(Dialog.goin_car) # type: ignore
        self.reButton.clicked.connect(Dialog.return_one) # type: ignore
        self.peopleButton.clicked.connect(Dialog.goin_peo) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title2.setText(_translate("Dialog", "校门监控"))
        self.reButton.setText(_translate("Dialog", "上一级"))
        self.video.setText(_translate("Dialog", "TextLabel"))
        self.peopleButton.setText(_translate("Dialog", "人流量监测"))
        self.carButton.setText(_translate("Dialog", "车流量监测"))
