# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mdui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1252, 795)
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(300, 10, 601, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.title.setObjectName("title")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(90, 180, 481, 381))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.video1 = QtWidgets.QLabel(self.frame)
        self.video1.setGeometry(QtCore.QRect(0, 0, 481, 381))
        self.video1.setObjectName("video1")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(700, 180, 481, 381))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.video2 = QtWidgets.QLabel(self.frame_2)
        self.video2.setGeometry(QtCore.QRect(0, 0, 481, 381))
        self.video2.setObjectName("video2")
        self.northcar = QtWidgets.QPushButton(Dialog)
        self.northcar.setGeometry(QtCore.QRect(150, 590, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.northcar.setFont(font)
        self.northcar.setObjectName("northcar")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 120, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(840, 110, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.northpeo = QtWidgets.QPushButton(Dialog)
        self.northpeo.setGeometry(QtCore.QRect(350, 590, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.northpeo.setFont(font)
        self.northpeo.setObjectName("northpeo")
        self.eastcar = QtWidgets.QPushButton(Dialog)
        self.eastcar.setGeometry(QtCore.QRect(740, 580, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.eastcar.setFont(font)
        self.eastcar.setObjectName("eastcar")
        self.eastpeo = QtWidgets.QPushButton(Dialog)
        self.eastpeo.setGeometry(QtCore.QRect(950, 580, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.eastpeo.setFont(font)
        self.eastpeo.setObjectName("eastpeo")

        self.retranslateUi(Dialog)
        self.eastcar.clicked.connect(Dialog.car_goin) # type: ignore
        self.northcar.clicked.connect(Dialog.car_goin) # type: ignore
        self.eastpeo.clicked.connect(Dialog.peo_goin) # type: ignore
        self.northpeo.clicked.connect(Dialog.peo_goin) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "内 蒙 古 大 学 监 控 系 统"))
        self.video1.setText(_translate("Dialog", "TextLabel"))
        self.video2.setText(_translate("Dialog", "TextLabel"))
        self.northcar.setText(_translate("Dialog", "北校门车流量监测"))
        self.label.setText(_translate("Dialog", "北校门监控"))
        self.label_2.setText(_translate("Dialog", "东校门监控"))
        self.northpeo.setText(_translate("Dialog", "北校门人流量监测"))
        self.eastcar.setText(_translate("Dialog", "东校门车流量监测"))
        self.eastpeo.setText(_translate("Dialog", "东校门人流量监测"))
