# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pepui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1255, 792)
        font = QtGui.QFont()
        font.setPointSize(16)
        Dialog.setFont(font)
        self.title2 = QtWidgets.QLabel(Dialog)
        self.title2.setGeometry(QtCore.QRect(580, 70, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title2.setFont(font)
        self.title2.setAlignment(QtCore.Qt.AlignCenter)
        self.title2.setObjectName("title2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(190, 150, 941, 481))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.video = QtWidgets.QLabel(self.frame)
        self.video.setGeometry(QtCore.QRect(0, 0, 941, 481))
        self.video.setObjectName("video")
        self.returnButton = QtWidgets.QPushButton(Dialog)
        self.returnButton.setGeometry(QtCore.QRect(20, 20, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.returnButton.setFont(font)
        self.returnButton.setObjectName("returnButton")
        self.car = QtWidgets.QLabel(Dialog)
        self.car.setGeometry(QtCore.QRect(170, 660, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.car.setFont(font)
        self.car.setObjectName("car")
        self.number = QtWidgets.QLabel(Dialog)
        self.number.setGeometry(QtCore.QRect(340, 660, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.number.setFont(font)
        self.number.setText("")
        self.number.setObjectName("number")
        self.title1 = QtWidgets.QLabel(Dialog)
        self.title1.setGeometry(QtCore.QRect(550, 70, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title1.setFont(font)
        self.title1.setText("")
        self.title1.setAlignment(QtCore.Qt.AlignCenter)
        self.title1.setObjectName("title1")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(160, 640, 341, 81))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.raise_()
        self.title2.raise_()
        self.frame.raise_()
        self.returnButton.raise_()
        self.car.raise_()
        self.number.raise_()
        self.title1.raise_()

        self.retranslateUi(Dialog)
        self.returnButton.clicked.connect(Dialog.return_home) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title2.setText(_translate("Dialog", "校门人流量监测"))
        self.video.setText(_translate("Dialog", "TextLabel"))
        self.returnButton.setText(_translate("Dialog", "返回"))
        self.car.setText(_translate("Dialog", "当前总人数："))
